<div id="appraisalid">
<nav>
{{#each this.appraisal}}

    <h4>{{this.name}}</h4>
    <a href={{this.assigntopost}}>
    <img src={{this.icon}} alt={{this.descrption}} height="42" width="42"> 
    <a>
    |
{{/each}}
|
</nav>
</div>